### PR TITLE
feat: introduce dashboard module

### PR DESCRIPTION
**Pull request by ggarg2**

### CODE REVIEW

**Comment by patrickmichalina** [comment]
Couple things:

- You need to add the .spec files for each component
- Cleanup the styling of the dashboard

**Comment by patrickmichalina** [comment]
I am also thinking this should be the 'ADMIN' module to use to adjust settings in the API

**Comment by ggarg2** [comment]
sure i will create spec.ts files.

**Comment by ggarg2** [comment]
spec.ts files are created
ng-lazy.js is not supporting window 10

**Review by patrickmichalina — APPROVED** [review]

**Pull request merged**
